import { Grid } from '@mui/material'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'

let handleChange = (event) => {

    switch (event.target.name) {
        case 'name':
            data.name = event.target.value;
            break;
        case 'username':
            data.username = event.target.value;
            break;
        case 'password':
            data.password = event.target.value;
            break;
        case 'toggle1':
            data.toggle1 = event.target.checked;
            break;
        default:
            break;
    }
    console.log('VALOR DEL TOGGLE: '+data.toggle1);
};


export default function Home(data) {
    return (
        <div>
            <Head>
                <title> New Exam</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <form className='form'>
                    <h1 className = {styles.title}> Create Exam </h1>

                    <div className = {styles.grid}>
                        <div className = {styles.card}>
                            <h2> Lets' create your account </h2>

                            <input id="examIdentifier" type="text" name='name' placeholder="Exam Identifier" onChange={handleChange} />
                            <input id="examPassword" type="text" name='username' placeholder="Password" onChange={handleChange} />
                            <input id="examTitle" type="text" name='password' placeholder="Title" onChange={handleChange}/>
                            <div>
                                <input type="checkbox" name="toggle1" onChange={handleChange}/>

                            </div>
                            <br />
                            <input type="submit" value="Create" />
                        </div>
                    </div>
                </form>
            </main>
        </div>
    )
}