import { Grid } from '@mui/material';
import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import QuestionBox from '../../components/ExamForm/QuestionBox'

export default function Home(data) {
    return (

        <div>
            <Head>
                <title>New Examn</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <main className={styles.main} />

            </Head>
            <div>
                <Grid>
                    <div className="card" style={{ width: "350px", height: "200px" }}>
                        <div className="card-body">

                            <form>
                                <label>
                                    Nombre del formulario:
                                    <input type='text' class="form-control" id='formularyName' />

                                </label>
                                <label>
                                    Código de acceso:
                                    <input type='password' class='form-control' id='accessCode' />
                                </label>

                                <div className='text-center'>
                                    <QuestionBox/>
                                </div>
                            </form>


                        </div>
                    </div>
                </Grid>
            </div>

        </div>




        /*
        <form>
                    <div class='mb-3'>
                        <label for='formularyName' class='form-label'>Nombre del formulario</label>
                        <input type='text' class="form-control" id='formularyName'/>
                    </div>
                    <div class='mb-3'>
                        <label for='accessCode' class='form-label'>Código de acceso</label>
                        <input type='password' class='form-control' id='accessCode'/>
                    </div>
                    <div class='text-center'>
                        {QuestionBox}
                    </div>
                    <Card>
                        <CardContent>
                            <div class='text-center'>
                                <button type='btn' class='btn btn-primary' >
                                    Crear pregunta
                                </button>
                            </div>
                        </CardContent>
                    </Card>
                </form>
        */
    )

}