import { Fab, AddIcon } from '@mui/material'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'

let data = {
    identifier: '',
    password: '',
    title: '',
    description: ''
}

let handleChange = (event) => {

    switch (event.target.name) {
        case 'identifier':
            data.identifier = event.target.value;
            break;
        case 'password':
            data.password = event.target.value;
            break;
        case 'title':
            data.title = event.target.value;
            break;
        case 'description':
            data.description = event.target.value;
        default:
            break;
    }
};

let addQuestion = (event) => {
    
}

async function handleSubmit(event) {
    event.preventDefault();
    const response = await fetch('http://localhost:3000/api/teacher/[id]', {    
        method: 'POST',
        body: JSON.stringify({ data }),
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        }
    })
    const responseData = await response.json();

    if(responseData.success){
        window.location.href = '/'
    }
}


export default function Home(data) {
    return (
        <div>
            <Head>
                <title> New Exam</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <form className='form'>
                    <h1 className = {styles.title}> Create Exam </h1>

                    <div className = {styles.grid}>
                        <div className = {styles.card}>
                            <h2> Lets' create a new examn </h2>
                            
                            <input id="identifier" type="text" name='identifier' placeholder="Exam Identifier" onChange={handleChange} />
                            <input id="password" type="text" name='password' placeholder="Password" onChange={handleChange} />
                            <input id="title" type="text" name='title' placeholder="Title" onChange={handleChange}/>
                            <input id="description" type="text" name='description' placeholder="Description" onChange={handleChange}/>
                            <div>
                                <input id="question" type="text" name='question' placeholder="New Question" onChange={handleChange}/>
                                <span>
                                    <button type = "submit"> + </button>
                                </span>
                            </div>
                            
                            {/* <Fab size="small" color="secondary" aria-label="add">
                                <AddIcon />
                            </Fab> */}
                            <p>
                                <br />
                                <input type="submit" value="Create" />
                            </p>
                        </div>
                    </div>
                </form>
            </main>
        </div>
    )
}