CREATE TABLE STUDENT(
ID SERIAL,
NAME VARCHAR(20),
USERNAME VARCHAR(20),
PASSW VARCHAR(20),
PRIMARY KEY(ID)

);

INSERT INTO STUDENT VALUES('1','A','E','0');

CREATE TABLE TEACHER (
ID SERIAL,
NAME VARCHAR(30),
USERNAME VARCHAR(20),
PASSW VARCHAR(20),
IDEXAMN VARCHAR(3),
PRIMARY KEY(ID)
);


CREATE TABLE TEACHER (
IDTEACHER SERIAL,
NAME VARCHAR(30),
USERNAME VARCHAR(20),
PASSW VARCHAR(20),
IDEXAMN VARCHAR(3),
PRIMARY KEY(IDTEACHER)
);

CREATE TABLE EXAMN(
ID VARCHAR(3),
CODE VARCHAR(3),
NAME VARCHAR(15),
IDTEACHER Varchar(3),
PRIMARY KEY (IDTEACHER)	
);

INSERT INTO TEACHER VALUES('1','A','T','0','A');
INSERT INTO EXAMN VALUES('A','Aa','EXAMN1','1');


SELECT * FROM TEACHER;
SELECT * FROM STUDENT;
SELECT * FROM EXAMN;

