CREATE TABLE STUDENT(
ID SERIAL,
NAME VARCHAR(20),
USERNAME VARCHAR(20),
PASSW VARCHAR(20),
PRIMARY KEY(ID)

);

INSERT INTO STUDENT VALUES('1','A','E','0');

SELECT * FROM STUDENT;


CREATE TABLE TEACHER (
ID SERIAL,
NAME VARCHAR(30),
USERNAME VARCHAR(20),
PASSW VARCHAR(20),
PRIMARY KEY(ID)
);

INSERT INTO TEACHER VALUES('1','A','T','0');

ALTER TABLE TEACHER ADD IDEXAMN VARCHAR(3);

SELECT * FROM TEACHER;


CREATE TABLE EXAMN(
ID VARCHAR(3),
CODE VARCHAR(3),
NAME VARCHAR(15),
PRIMARY KEY (ID)	
);