import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function SingUp() {

    let data = {
        id: 0,
        name: '',
        username: '',
        password: '',
        toggle1: true
    }

    async function handleSubmit(event) {
        event.preventDefault();
        const response = await fetch('/api/account/verifyAccount', {
            method: 'POST',
            body: JSON.stringify({ data }),
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        })
        const responseData = await response.json();

        if(responseData.success){
            window.location.href = '/'
        }
    }


    let handleChange = (event) => {

        switch (event.target.name) {
            case 'name':
                data.name = event.target.value;
                break;
            case 'username':
                data.username = event.target.value;
                break;
            case 'password':
                data.password = event.target.value;
                break;
            case 'toggle1':
                data.toggle1 = event.target.checked;
                break;
            default:
                break;
        }
        console.log(data.toggle1)
    };


    return (

        <div className={styles.container}>
            <Head>
                <title>SignUp</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <form className='form' onSubmit={handleSubmit}>
                    <h2 className={styles.title}>Sign Up</h2>

                    <div className={styles.grid}>
                        <div className={styles.card}>
                            <h2>Lets' create your account</h2>

                            <input id="name" type="text" name='name' placeholder="Full Name" onChange={handleChange} />
                            <input id="username" type="text" name='username' placeholder="username" onChange={handleChange} />
                            <input id="password" type="password" name='password' placeholder="Password" onChange={handleChange}/>
                            <div>
                                <input type="checkbox" name="toggle1" onChange={handleChange}/>

                            </div>
                            <br />
                            <input type="submit" value="Create" />
                        </div>
                    </div>
                </form>
            </main>
        </div>

    )
}

