import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (

        <div className={styles.container}>
            <Head>
                <title>SignUp</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h2 className={styles.title}>Sign Up</h2>

                <div className={styles.grid}>
                    <div className={styles.card}>
                        <h2>Lets' create your account</h2>

                        <input id="name" type="text" placeholder="Full Name" />
                        <input id="username" type="text" placeholder="Username" />
                        <input id="password" type="password" placeholder="Password" />
                        <br />                    
                        <button id="CreateAccountButton">Create</button>                                               
                    </div>

                </div>
            </main>


        </div>

    )
}